# SPDX-FileCopyrightText: (c) 2024 Inseo Oh <dhdlstjtr@gmail.oom>
#
# SPDX-License-Identifier: BSD-2-Clause

ifndef YJK_PROJECT_ROOT
$(error YJK_PROJECT_ROOT is not set! Make sure you run the top-level Makefile)
endif

YJK_TARGET_NAME = hellosvc
YJK_TARGET_TYPE = EXEC

YJK_OBJS = main.o strfmt.o

YJK_INSTALL_DIR = ${YJK_BOOT_ROOT}/yjk

include $(YJK_PROJECT_ROOT)/support/common.mk

